### ISSUE TITLE
Template for text field

### ISSUE THREAD

**Issue by eporocrail** [tfry-git/EmbAJAX#1]
It would be a nice feature if it would be possible to apply a template to insert data into a text field. One of the first templates which comes into mind would be a template for an IP-address. Next to application of the template the length of the field would need restriction also.

Ellard Postma

**Comment by tfry-git** [comment]
Ok, I have implemented something like this, now, although it is not quite as automatic as you had in mind. You need to set the placeholder and validation pattern, manually, at least for now.

Example given in "Inputs". Let me know what you think.

**Comment by eporocrail** [comment]
It presents a template of the expected input. No handling/validation of input.
Helps the user inserting data.
