### ISSUE TITLE
 Esp8266 spiffs

### ISSUE THREAD

**Issue by Stefananderssonster** [tfry-git/EmbAJAX#11]
Hello,

If a would like to use the esp8266 spiffs memory to store a image or css style sheet how can I implement that? I've seen some example with the ESPAsyncWebServer library. Is the same code usable with EmbAJAX?

**Comment by tfry-git** [comment]
Hi!

This is somewhat complicated by the fact that - by default - EmbAJAX uses ESP8266WebServer on the esp8266, not ESPAsyncWebServer. So two options:

### Using ESP8266WebServer:
```
// Among the other includes, add
#include <FS.h>

// In setup(), add
void setup() {
// [...]
// init SPIFFS
   SPIFFS.begin();
// define a handler routine to serve file from SPIFFS when "myuri" is requested:
   server.on("/myuri", [=]() {
     File file = SPIFFS.open("/mySpiffsPath.html", "r");
     server.streamFile(file, "text/html");
     file.close();
   });
}

```

### Using ESP8266WebServer:
For this, you will have to change the way EmbAJAX is set up. The following should do the trick:
```
// Before #include <EmbAJAX.h>, add
#include <ESPAsyncWebServer.h>
#include <ESP8266WiFi.h>
#define EmbAJAXOutputDriverWebServerClass ESPAsyncWebServer
#include "EmbAJAXOutputDriverGeneric.h"
// for compatibility with the remainder of the code examples
#define EmbAJAXOutputDriverESP8266 EmbAJAXOutputDriver
```

EmbAJAX will now be using ESPAsnyWebServer as the output backend. Your SPIFFS example should work out of the box. Essentially you just need to add your handler in setup():

```
void setup() {
// [...]
// define a handler routine to serve file from SPIFFS when "myuri" is requested:
  server.on("/myuri", HTTP_GET, [](AsyncWebServerRequest *request) {
    request->send(SPIFFS, "/mySpiffsPath.html");
  });
}
```

**Comment by V3N0MX92** [comment]
Can anyone include a simple example with ESP8266WebServer and FS.h ? I have some issues trying to style the CSS externally from a .css file with EmbAJAX. A full example would help. Thanks!

**Comment by tfry-git** [comment]
Hi!

Do you know the basics of using  SPIFFS on your ESP8266? I.e. do you know how to upload files to SPIFFS? 'cause that may be the hardest part to get working, really. After that, start from the EmbAJAX->Blink Example. Modifiy as follows:

1.  Right below "#include <EmbAJAX.h>", add
```#include <FS.h>```
2. Right below ```driver.installPage(&page, "/", updateUI);``` insert
```SPIFFS.begin();
  server.on("/test.html", [=]() {
     File file = SPIFFS.open("/test.html", "r");
     server.streamFile(file, "text/html");
     file.close();
   });```
3. Save the sketch to a read-write location in your sketchbook.
4. Press Ctrl+K to open a file browser. Add a subdirectory "data", and place some small HTML file called "test.html" into it.
5. Upload the Sketch.
6. Upload the Data (Tools->ESP8266 Sketch Data Upload).

That should be it. If this works for you, but does not solve your issue, please be a bit more specific, what exactly you need help with.

**Comment by V3N0MX92** [comment]
Hi!
Yes I think I know the basics of working with SPIFFS on ESP8266. I tried your example above and **it works as it should** 

I also added a style.css using the same method and I can style the page test.html from style.css.

1. How I did it (not sure if this is the best idea):

```
SPIFFS.begin();
  server.on("/test.html", [=]() {
     File file1 = SPIFFS.open("/test.html", "r");
     server.streamFile(file1, "text/html");
     file1.close();
   });
  server.on("/style.css", [=]() {
     File file2 = SPIFFS.open("/style.css", "r");
     server.streamFile(file2, "text/css");
     file2.close();
   });

```

2. My problem: 
I would like to include for example some styling in EmbAJAXPage when the root page is loaded from a .css file stored on the flash file system (SPIFFS). 
I uploaded the .css file the same way as above and when I access http://192.168.4.1/style.css I can see the code but on the main page I get no styling. Here is where I need some help. 

I used your "Styling example" as following:
` #include <EmbAJAX.h>`
`#include <FS.h>`

`MAKE_EmbAJAXPage(page, "EmbAJAX example - Styling",`
   `"<link rel=\"stylesheet\" href=\"style.css\">\n"`
  `new EmbAJAXPushButton("my_button1", "Nothing", handleButton),`
  `new EmbAJAXPushButton("my_button2", "Round", handleButton),`
 ` )`

`void setup() {`
  `WiFi.mode(WIFI_STA);`
  `WiFi.begin(ssid,password);`

 ` // Tell the server to serve our EmbAJAX test page on root`
 ` // installPage() abstracts over the (trivial but not uniform) WebServer-specific instructions to do so`
 ` driver.installPage(&page, "/", updateUI);`
     `SPIFFS.begin();`
  ` server.on("/style.css", [=]() {`
     `File file = SPIFFS.open("/style.css", "r");`
    ` server.streamFile(file, "text/css");`
     `file.close();`
  ` });`
`  server.begin();`
`}`

`void updateUI() {`
  `// This page does nothing`
`}`

`void loop() {`
  `driver.loopHook();`
`}`

In the style.css file I added .my_button1 and .mybutton2 as following:
.my_button1 {
 box-shadow:inset 0px 1px 0px 0px #ffffff;
  background-color:#f9f9f9;
  display:inline-block;
  cursor:pointer;
  color:#666666;
  ont-family:Arial;
  font-size:15px;
  font-weight:bold;
  padding:6px 24px;
  text-decoration:none;
  text-shadow:0px 1px 0px #ffffff; } ... same for button2.

Can you help me with this issue? Maybe there is a simple solution but I don't get where I mess up.

Thank you!

**Comment by tfry-git** [comment]
> .my_button1

^ This is probably the problem. ```my_button1``` isn't the class, but the id of the button, i.e. you'll have to write
```
#my_button1 { ... }
```

Alternatively, you can select all buttons at once by the element name, i.e.
```
button { ... }
```

(In case of problems it's often helpful to just copy the generated HTML sources (Ctrl+U in Firefox and Chrome), and paste them and the CSS into a tool like JSFiddle.com. Getting the CSS right on the first attempt is pretty much impossible in most cases, and this allows for much faster testing and adjusting, until you've figured out the correct CSS.)

**Comment by V3N0MX92** [comment]
Yes. You are right, it was a CSS styling problem. Thank you again for the explanation !
