### ISSUE TITLE
Slider example from README not working on ESP8266

### ISSUE THREAD

**Issue by kwerdenker** [tfry-git/EmbAJAX#13]
Using the slider example code from the README, when visiting the website I get this output. Looks to me as if there are errenous bytes send before the header and content?
```
70
HTTP/1.1 200 OK
Content-Type: text/html
Accept-Ranges: none
Transfer-Encoding: chunked
Connection: close


0

<HTML><HEAD><TITLE>EmbAJAXTest</TITLE>
<SCRIPT>
var serverrevision = 0;
function doRequest(id='', value='') {
    var req = new XMLHttpRequest();
    req.timeout = 10000;
    if(window.ardujaxsh) window.ardujaxsh.out();
    req.onload = function() {
       doUpdates(JSON.parse(req.responseText));
       if(window.ardujaxsh) window.ardujaxsh.in();
    }
    if(id) {
       req.onerror = req.ontimeout = function() {
          serverrevision = 0;
       }
    }
    req.open('POST', document.URL, true);
    req.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
    req.send('id=' + id + '&value=' + encodeURIComponent(value) + '&revision=' + serverrevision);
}
function doUpdates(response) {
    serverrevision = response.revision;
    var updates = response.updates;
    for(i = 0; i < updates.length; i++) {
       element = document.getElementById(updates[i].id);
       changes = updates[i].changes;
       for(j = 0; j < changes.length; ++j) {
          var spec = changes[j][0].split('.');
          var prop = element;
          for(k = 0; k < (spec.length-1); ++k) {
              prop = prop[spec[k]];
          }
          prop[spec[spec.length-1]] = changes[j][1];
       }
    }
}
function doPoll() {
    doRequest();
}
setInterval(doPoll,1000);
</SCRIPT>
</HEAD>
<BODY><FORM autocomplete="off" onSubmit="return false;">
<h1>This is a test</h1><p>The value you set in the following slider: <input type="range" id="slider" min=0 max=500 value=400 onChange="doRequest(this.id, this.value);"/> is sent to the server...</p><p>... which displays it here: <b><span id="display">400</span>
</b></p>
</FORM></BODY></HTML>
```

Using the latest version from the master branch, compiling through PlatformIO

**Comment by tfry-git** [comment]
Hi!

Yes this does look like some erroneous bytes added to the header, but I don't know where these are coming from. I don't think it's from within EmbAJAX.

To make extra sure, I've just tried on a fresh installation, and I cannot reproduce the issue. Are you sure you are working with an unmodified version of the ESP8266 core (esp. the Webserver class)? Try updating your ESP8266 core.

Just to make sure we are on the same page (although it should not make a difference): You are using the "plain" example in the readme, *without* the extra includes for using ESPAsyncWebserver, right?

**Comment by kwerdenker** [comment]
I thought I had the most recent version but apparently there was an update in the meantime. Updated all packages, recompiled and now everything is working as expect.

Sorry for the scare! I thought I had tried everything in the book but apparently missed the important "update your stuff!" step 😅
