### ISSUE TITLE
(Optionally) allow immediate updates while dragging slider

### ISSUE THREAD

**Issue by tfry-git** [tfry-git/EmbAJAX#14]
Suggested, here: https://www.instructables.com/id/Easy-ESP8266-Arduino-Core-Web-Controls-With-EmbAJA/?commentId=CHCMGMLK4P8MIAM

**Comment by Barnstormer50** [comment]
Hi. It was me that raised this issue as above. So I’ve joined github and will comment further here. You suggested a “quick and dirty” solution which I have implemented and tested - it works on IE on Windows 10 and on Safari on an IPAD. Also I’ve tried using a number of smart phones and only found a problem with my Motorola - no matter what browser I use I get “504 Gateway Timeout error”. It will log onto the access point I’ve created but just times out and displays nothing apart from the error message. Not asking for solution - I guess it’s most likely that the phone is the problem. Anyway my project has progressed very well thanks to the head start your work has given me - I now have a fully functional motor controller, and I’m starting to look at a few styling tweaks. 
Thanks again for your help.

**Comment by tfry-git** [comment]
Implemented in #43 / #44
