### ISSUE TITLE
Including simple variables into EmbAJAX page

### ISSUE THREAD

**Issue by V3N0MX92** [tfry-git/EmbAJAX#15]
Very nice library indeed. I have a question though. I want to display some variables on the webpage (for example the hour from an NTP server between some sliders). Before using the library I would just write into html page() like the following example page+="<b>Time:</b>"; page+=hour; and the HTML would display my variable after the "Time:" string. In this case how do I use your MAKE_EmbAJAXPage(page,....) to display some variables which are not sliders,buttons or anything else included in the .h file? How do you suggest to do this? Thanks!

**Comment by tfry-git** [comment]
[EmbAJAXMutableSpan](https://tfry-git.github.io/EmbAJAX/api/classEmbAJAXMutableSpan.html) is the class you are looking for.

You embed it into an EmbAJAX page like any other control. When you want to display something, use

```
EmbAJAXMutableSpan my_span;
// ...
my_span.setValue("Something");  // or
my_span.setValue(formatted_time.c_str());  // or
my_span.setValue("If you want you HTML, here, set the second parameter to <i>true</i>", true);
```

**Comment by V3N0MX92** [comment]
Thank you. This library makes everyone's life easier. 
How would you suggest do display variables which are not integers with EmbAJAXMutableSpan function? I made for example a thermostat button for + and one for -  and I want to add (with button 1) and subtract (with button 2) 0.5 degrees per click.

So let's say we have the code below:
 
`float button_count = 0;`
`void button1(EmbAJAXPushButton*) { button_count+=0.5; }`
`EmbAJAXPushButton buttonplus("button", "+", button1);`
`EmbAJAXMutableSpan button_1("button_1");`
`char button_1_buf[BUFLEN];`

In updateUI() what should I define  button_1 to be able to display float values?

Thanks in advance!

**Comment by tfry-git** [comment]
If I understand you correctly, your question is how to display a `float` value in `EmbAJAXMutabableSpan`. The examples do show it for `int`, but in fact, it is a bit different for `float`, since there is no `ftoa()` to match `itoa()`.

I guess the easiest is to use `String` for conversion, instead:

```
float button_count = 0.1;
String button_count_display_buffer;
// [...]
void updateUI() {
   button_count_display_buffer = String(button_count);
   button_1.setValue(button_count_display_buffer.c_str());
}
```

**Comment by V3N0MX92** [comment]
Perfect. Thank you very much for the explanations and for the fast replies.
