### ISSUE TITLE
call of overloaded 'selectOption(int)' is ambiguous

### ISSUE THREAD

**Issue by Win-doze** [tfry-git/EmbAJAX#20]
I am sure this is just due to my incompetence but when I try to set the first radio button from the Arduino loop function I get this error:
EmbAJAX_Web_Boiler_controller:334:30: error: call of overloaded 'selectOption(int)' is ambiguous
          Power.selectOption(0);    
If I were to set any non zero radio button the code compiles.
My workaround has been to increase the number of radio buttons by one and set the first as N/A. The code is attached as a file so you can see it in its entirety.

Your library is really impressive and more useful than others I have tried, I am attempting to avoid web based solutions like Blynk as the internet may not be available in the location I am deploying the device.
the software is designed to operate a steam generating boiler from a SONOFF R2 Basic. I am trying to use both the pushbutton on the SONOFF to turn the boiler on and off along with controlling the power of the heating element as well. In addition having a web interface that accomplishes the same thing. This requires the web page to be updated from the physical button press operation, hence trying to set the radio button from the Arduino software.
Are you able to advise where I am going wrong with this bit of the code? (It is the last line before the closing braces)
I appreciate any advice you can give.

`#include <FS.h>
#include <EmbAJAX.h>
#include <DNSServer.h>
#include <OneWire.h>
#include <DallasTemperature.h>
#include <ArduinoOTA.h>
#include <Ticker.h>
#include <EmbAJAXExtensions.cpp>
Ticker timer;

ESP8266WebServer http ( 80 );
#define LEDPIN 13

uint16_t status;
uint16_t button1;
uint16_t Temp1LabelId;
uint16_t Temp2LabelId;
uint16_t switchOne;
uint16_t switchTwo;
int gpio13Led = 13;
int gpio12Relay = 12;
int gpio14zeroX = 14;
int BUTTONPIN = 0; //set up variable BUTTONPIN as the pin to which the button connects
#define myZeroXBit (1<<14)
#define myLedBit (1<<13)
int ButtonValue; // set up variable to hold value input from BUTTONPIN. 
int Old_ButtonValue; //set up variable to determine the previous value of ButtonValue
int ProcessingPush = 0; // Used to check if a push is being processed, 1 being true = on, 0 being false = off
byte LightOn = 0; // Used to determine whether the light is on or off, 1 being true = on, 0 being false = off
unsigned long startTime = 0; //determines begginning of button press

//Macros For SSR
#define ssr_on WRITE_PERI_REG( PERIPHS_GPIO_BASEADDR + 4, myZeroXBit ); //WRITE_PERI_REG( PERIPHS_GPIO_BASEADDR + 8, myLedBit ); //fast access to the pins
#define ssr_off WRITE_PERI_REG( PERIPHS_GPIO_BASEADDR + 8, myZeroXBit ); //WRITE_PERI_REG( PERIPHS_GPIO_BASEADDR + 4, myLedBit ); //fast access to the pins

//Volatile variables which could be modified in both standard code or interrupt routines
volatile int interrupts;
volatile uint8_t demandedpower=0;
volatile uint8_t powercount=1;
//************************************************************************

// ISR to Fire when Timer is triggered
void ICACHE_RAM_ATTR onTime() {

  // Re-Arm the timer as using TIM_SINGLE
  timer1_write(100000);//12us

  //The actual SSR bit...
    powercount = powercount + demandedpower;
      if (powercount < demandedpower){ // powercount has overflowed so time to turn on the triac
        ssr_on;
      }
      else{
        ssr_off;
      }
}
 // end of ISR (INT0_vect) ********************************************

// Data wire is plugged TO GPIO 2
#define ONE_WIRE_BUS 2

// Setup a oneWire instance to communicate with any OneWire devices (not just Maxim/Dallas temperature ICs)
OneWire oneWire(ONE_WIRE_BUS);

// Pass our oneWire reference to Dallas Temperature. 
DallasTemperature sensors(&oneWire);

// Number of temperature devices found
int numberOfDevices;

// We'll use this variable to store a found device address
DeviceAddress tempDeviceAddress;

// Set up web server, and register it with EmbAJAX. Note: EmbAJAXOutputDriverWebServerClass is a
// convenience #define to allow using the same example code across platforms
EmbAJAXOutputDriverWebServerClass server(80);
EmbAJAXOutputDriver driver(&server);

// Define the main elements of interest as variables, so we can access to them later in our sketch.
//const char* modes[] = {"On", "Blink", "Off"};
const char* pmodes[] = {"N/A", "On", "Off"};
//EmbAJAXRadioGroup<3> mode("mode", modes);
//EmbAJAXSlider blinkfreq("blfreq", 0, 1000, 100);   // slider, from 0 to 1000, initial value 100
EmbAJAXRadioGroup<3> Power("Power", pmodes);
EmbAJAXSlider DemandedPower("DmdPwr", 0, 255, 30);   // slider, from 0 to 255, initial value 30
EmbAJAXMutableSpan display1("display1");         // a plain text display
EmbAJAXMutableSpan display2("display2");         // a plain text display

// Define a page (named "page") with our elements of interest, above, interspersed by some uninteresting
// static HTML. Note: MAKE_EmbAJAXPage is just a convenience macro around the EmbAJAXPage<>-class.
MAKE_EmbAJAXPage(page, "EmbAJAX example - Blink", "",
 // "<link rel=\"stylesheet\" href=\"style.css\">\n",
 // new EmbAJAXStatic("<h1>Control the builtin LED</h1><p>Set the LED to: "),
//  &mode,
//  new EmbAJAXStatic("</p><p>Blink frequency: <i>SLOW</i>"),
//  &blinkfreq,
//  new EmbAJAXStatic("<i>FAST</i></p>"),
  new EmbAJAXStatic("<h1>Control the Boiler</h1><p>Set the Power to: "),
  &Power,
  new EmbAJAXStatic("</p><p>Boiler Power: </p><p><i>Min</i>"),
  &DemandedPower,
  new EmbAJAXStatic("<i>Max</i></p>"),
  new EmbAJAXStatic("Head Temperature: <b>"),
  &display1,
  new EmbAJAXStatic("&deg;C</b></p>"),
  new EmbAJAXStatic("Boiler Temperature: <b>"),
  &display2,
  new EmbAJAXStatic("&deg;C</b></p>"),
  new EmbAJAXStatic("Connection status: "),
  new EmbAJAXConnectionIndicator(),
  new EmbAJAXStylesheet("style.css"),
  new EmbAJAXViewport
)

void setup() {
  Serial.begin(115200);
  // Example WIFI setup as an access point. Change this to whatever suits you, best.
  WiFi.mode(WIFI_AP);
  WiFi.softAPConfig (IPAddress (192,168,4,1), IPAddress (0,0,0,0), IPAddress (255,255,255,0));
  WiFi.softAP("EmbAJAXTest", "12345678");

  
//Set all outputs to a safe state
  pinMode(gpio14zeroX, OUTPUT); 
  digitalWrite(gpio14zeroX, LOW);  // Turn off SSR
  pinMode(gpio13Led, OUTPUT);
  digitalWrite(gpio13Led, HIGH);   // Turn off Green LED
  pinMode(gpio12Relay, OUTPUT);
  digitalWrite(gpio12Relay, LOW);  // Turn off the Relay
  pinMode(BUTTONPIN, INPUT);// Set up BUTTONPIN as an Input

// Start up the Dallas one wire library
  sensors.begin();

  // ArduinoOTA Setup
  // Port defaults to 8266
  // ArduinoOTA.setPort(8266);

  // Hostname defaults to esp8266-[ChipID]
  // ArduinoOTA.setHostname("myesp8266");

  // No authentication by default
  // ArduinoOTA.setPassword((const char *)"123");

  ArduinoOTA.onStart([]() {
    Serial.println("Start");
  });
  ArduinoOTA.onEnd([]() {
    Serial.println("\nEnd");
  });
  ArduinoOTA.onProgress([](unsigned int progress, unsigned int total) {
    Serial.printf("Progress: %u%%\r", (progress / (total / 100)));
  });
  ArduinoOTA.onError([](ota_error_t error) {
    Serial.printf("Error[%u]: ", error);
    if (error == OTA_AUTH_ERROR) Serial.println("Auth Failed");
    else if (error == OTA_BEGIN_ERROR) Serial.println("Begin Failed");
    else if (error == OTA_CONNECT_ERROR) Serial.println("Connect Failed");
    else if (error == OTA_RECEIVE_ERROR) Serial.println("Receive Failed");
    else if (error == OTA_END_ERROR) Serial.println("End Failed");
  });
  ArduinoOTA.begin();
  Serial.println("Ready");
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());
  if (!SPIFFS.begin())
  {
    // Serious problem
    Serial.println("SPIFFS Mount failed");
  } else {
    Serial.println("SPIFFS Mount succesfull");
  }
   server.on("/style.css", [=]() {
     File file1 = SPIFFS.open("/style.css", "r");
     server.streamFile(file1, "text/css");
     file1.close();
   });
  

  // Tell the server to serve our EmbAJAX test page on root
  // installPage() abstracts over the (trivial but not uniform) WebServer-specific instructions to do so
  driver.installPage(&page, "/", updateUI);
  server.begin();

  //Initialize Ticker every 0.5s timer interrupts
  timer1_attachInterrupt(onTime); // Add ISR Function
  timer1_enable(TIM_DIV16, TIM_EDGE, TIM_SINGLE);
  /* Dividers:
    TIM_DIV1 = 0,   //80MHz (80 ticks/us - 104857.588 us max)
    TIM_DIV16 = 1,  //5MHz (5 ticks/us - 1677721.4 us max)
    TIM_DIV256 = 3  //312.5Khz (1 tick = 3.2us - 26843542.4 us max)
  Reloads:
    TIM_SINGLE  0 //on interrupt routine you need to write a new value to start the timer again
    TIM_LOOP  1 //on interrupt the counter will start with the same value again
  */
  
  // Arm the Timer for our 20ms Interval
  timer1_write(100000); // 100000 / 5 ticks per us from TIM_DIV16 == 20,000 us interval 
}

char buf[16];
  String button_count_display_buffer1;
  String button_count_display_buffer2;
void updateUI() {
  // Enabled / disable the slider. Note that you could simply do this inside the loop. However,
  // placing it here makes the client UI more responsive (try it).
 // blinkfreq.setEnabled(mode.selectedOption() == 1);
  DemandedPower.setEnabled(Power.selectedOption() == 1);
  demandedpower = DemandedPower.intValue();
}

void loop() {

  float Temp1;
  float Temp2;
  byte PowerSet;
  static unsigned long  ramptime = 0;
  static unsigned long oldTime = 0;

  // handle network. loopHook() simply calls server.handleClient(), in most but not all server implementations.
  driver.loopHook();
  ArduinoOTA.handle();
  
/*  // And these lines are all you have to write for the logic: Access the elements as if they were plain
  // local controls
  if (mode.selectedOption() == 1) { // blink
      digitalWrite(LEDPIN, (millis() / (1100 - blinkfreq.intValue())) % 2);
  } else {  // on or off
      digitalWrite(LEDPIN, mode.selectedOption() != 0);
  }*/

// And these lines are all you have to write for the logic: Access the elements as if they were plain
  // local controls
/*  if (Power.selectedOption() == 0) {
      digitalWrite(gpio12Relay, false);
  } else {  // on or off
      digitalWrite(gpio12Relay, true);
  }*/

  if (millis() - oldTime > 2000) {
      sensors.requestTemperatures(); // Send the command to get temperatures
    if(sensors.getAddress(tempDeviceAddress, 1)){
      Temp1 = sensors.getTempC(tempDeviceAddress);
      // Print the data
      button_count_display_buffer1 = String(Temp1);
      display1.setValue(button_count_display_buffer1.c_str());
    }
//    button_count_display_buffer = "0.00";
    if(sensors.getAddress(tempDeviceAddress, 0)){
      Temp2 = sensors.getTempC(tempDeviceAddress);
      // Print the data
      button_count_display_buffer2 = String(Temp2);
      display2.setValue(button_count_display_buffer2.c_str());
    }
    oldTime = millis();
  }

  // Start of Button Processing Routine
  //
  //
  
   ButtonValue = digitalRead(BUTTONPIN); //digitalRead tells us if the value for this pin is HIGH or LOW
                                        //when button is pushed down digitalRead(BUTTONPIN) returns HIGH
    if((Power.selectedOption() == 2) && (ProcessingPush == 0)){
      LightOn = 0;
    }
    if((Power.selectedOption() == 1) && (ProcessingPush == 0)){
      LightOn = 1;
    }
    if((ButtonValue == LOW) && (Old_ButtonValue == HIGH)) { //a condition that asserts if ButtonValue is read as LOW (button is pushed)
                                                            //AND was previously HIGH and not already processing a push
      LightOn = 1 - LightOn; // this alternates LightOn to be either 1 or 0 (1 being light on, 0 light off)
      ProcessingPush = 1; // start processing this push
      startTime = millis(); // capture a time at button press
      
      while((millis() - startTime) < 10){
        } //for debouncing purposes, putting in a delay so that only one button press is registered
    }

    

    if((ButtonValue == LOW) && (Old_ButtonValue == LOW)){ // conditions to tell if the button is being held down
        if(LightOn == 1 && (millis() - startTime) > 200){ //if the button is held for more than 20ms
            demandedpower ++; //incrementally increase demandedpower
            if(demandedpower > 255){ //once demandedpower reaches 255
                   demandedpower = 0; // reset the LED back to 0
               }
               DemandedPower.setValue(demandedpower);
            ramptime = millis();
           while((millis() - ramptime) < 35){
        } //delay so demandedpower doesn't change too quickly (longer the delay, longer it takes to reach max)

              
          }
      }

    if((ButtonValue == HIGH) && (Old_ButtonValue == LOW) && (ProcessingPush == 1)) { //a condition that asserts if ButtonValue is read as HIGH (button is not pushed)
                                                            //AND was previously LOW and processing a push - end of push
      ProcessingPush = 0; // end processing this push  
    }                                                    
    Old_ButtonValue = ButtonValue; //after the above code has been executed, giving Old_ButtonValue the ButtonValue to detect the moment of button press.
    
    if(LightOn == 1) { //when light clicks on
         digitalWrite(gpio12Relay, HIGH);  // Turn on the Relay
         digitalWrite(gpio13Led, LOW);   // Turn on Green LED
         Power.selectOption(1);
    } else {
         digitalWrite(gpio12Relay, LOW);  // Turn off the Relay
         digitalWrite(gpio13Led, HIGH);   // Turn off Green LED
         demandedpower = 0;
         Power.selectOption(0);    
    }
 
}`

**Comment by tfry-git** [comment]
> I am sure this is just due to my incompetence but when I try to set the first radio button from the Arduino loop function I get this error:
EmbAJAX_Web_Boiler_controller:334:30: error: call of overloaded 'selectOption(int)' is ambiguous
Power.selectOption(0);
If I were to set any non zero radio button the code compiles.

Thanks for reporting, and thanks for the positive feedback!

You can either call like this:
```
Power.selectOption((uint8_t) 0);
```
or try again after a git pull.

**Comment by Win-doze** [comment]
Thank you for your speedy reply. Your suggestion worked beautifully.
