### ISSUE TITLE
Using EmbAJAX to display a graph

### ISSUE THREAD

**Issue by Win-doze** [tfry-git/EmbAJAX#21]
Sorry this is really a question rather than an issue. I am trying to modify your two web page example to show instant temperature readings on page 1 and a graph of readings on page 2. I have managed with the help of your examples and reading thru the issues, how to create a really nice page 1 with updating temperature readings, graphics, styling and SPIFFS. But I don't have a clue how to create the graphs on page two. I am trying to use Charts.js and with my inept hacking can get this following text to display a barchart on codepen, so at least I have an inkling how  Charts.js works. Can you offer me some tips on how to translate this to work as an EmbAJAX page. From there I will be able to alter the chart to a graph and the fun will begin with datalogging! By the way if you think that there is a simpler way to display graphs please let me know.
Thanks for your time.

\<!DOCTYPE HTML><html>
\<head>
 \<meta name="viewport" content="width=device-width, initial-scale=1">
 \<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
  \<style>
    body {
      min-width: 310px;
    	max-width: 800px;
    	height: 400px;
      margin: 0 auto;
    }
    h2 {
      font-family: Arial;
      font-size: 2.5rem;
      text-align: center;
    }
  \</style>
\</head>
  \<canvas id="myChart" width="400" height="400"></canvas>
\<script>
var ctx = document.getElementById('myChart');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
        datasets: [{
            label: '# of Votes',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
</script>
</html>

**Comment by tfry-git** [comment]
Hi!

You'll want to look into [EmbAJAXScriptedSpan](https://tfry-git.github.io/EmbAJAX/api/classEmbAJAXScriptedSpan.html). Use may or may not want to use this class to insert your script code into your page 2. However, the thing you really want to add via EmbAJAXScriptedSpan is:

```
this.receiveValue = function(value) { 
   myChart.updateChartToNewValue(value);
};
```

This allows you to send new values from the server via ```EmbAJAXScriptedSpan::setValue()```.

A very crude example of using this class is also given in the "Inputs" example.

I hope that's enough to get the idea. Otherwise just ask.

**Comment by Win-doze** [comment]
Thanks for your tips, I am not sure I am using EmbAJAXSpan correctly as my graph appears to have 2 zero values in addition to every point I am plotting. It should be a straight line at 25.5 with 1/3rd of the data points. You will see looking at the bottom axis three points all have the same time value!
<img width="1413" alt="Screen Shot 2020-05-03 at 21 19 32" src="https://user-images.githubusercontent.com/776159/80924911-e6c31c00-8d83-11ea-9824-a72b15188ab5.png">
I did wonder if it had anything to do with my other code so after two days of struggling I decided to write the simplest code and webpage I could to see if I could troubleshoot the issue. I still can't fathom what the problem is. I have attached the program to this response, if you have the time to see if I am doing something stupid with your software I would appreciate it. It should run on any ESP8266 system, I have just tested it on a Wemos D1. (The original program is destined for a SONOFF where it behaves exactly the same.) Once I this simple program running I am more than happy for it to be used in the examples to help someone else.

`/* Basic usage example for EmbAJAX library:
 * Provide a very basic graph using Charts.js.
 * 
 * 
 * This example code is in the public domain (CONTRARY TO THE LIBRARY ITSELF). */

#include <EmbAJAX.h>
#include <EmbAJAXScriptedSpan.h>
#include <ESP8266WiFiMulti.h> 

ESP8266WiFiMulti wifiMulti;     // Create an instance of the ESP8266WiFiMulti class, called 'wifiMulti'
const char* APssid = "EmbAJAXGraph";
const char* APpassword = "1234567890";
const char* ssid1 = "??????";
const char* password1 = "??????";
const char* ssid2 = "??????";
const char* password2 = "??????";

// Set up web server, and register it with EmbAJAX. Note: EmbAJAXOutputDriverWebServerClass is a
// convenience #define to allow using the same example code across platforms
EmbAJAXOutputDriverWebServerClass server(80);
EmbAJAXOutputDriver driver(&server);

// Define the main elements of interest as variables, so we can access to them later in our sketch.
EmbAJAXScriptedSpan m_script_t("m_script_t", "this.receiveValue = function(value) {values.push(value);var time = new Date().toLocaleTimeString();timestamp.push(time);showGraph()}");


// Define a page (named "page") with our elements of interest, above, interspersed by some uninteresting
// static HTML. Note: MAKE_EmbAJAXPage is just a convenience macro around the EmbAJAXPage<>-class.
MAKE_EmbAJAXPage(page, "Demo Graph", "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js\"></script>",
    new EmbAJAXStatic("<h1>Temperature Graph</h1>"),
    new EmbAJAXStatic("<body><div class=\"chart-container\" position: relative; height:350px; width:\"100%\"><canvas id=\"Chart\" width=\"400\" height=\"200\"></canvas></div>"),
    new EmbAJAXStatic("<p>This display shows the graph of temperature"),
    new EmbAJAXStatic("<script> var values = [];var timestamp = [];function showGraph(){"),
    new EmbAJAXStatic("var ctx = document.getElementById('Chart').getContext('2d');"),
    new EmbAJAXStatic("var myChart = new Chart(ctx, {type: 'line',data: {labels: timestamp, datasets: [{label: \"Temperature °C\",data: values}]}})}"),
    new EmbAJAXStatic("window.onload = function() {console.log(new Date().toLocaleTimeString());showGraph()}"),
    new EmbAJAXStatic("</script>"),
    &m_script_t
)


void setup() {
  Serial.begin(115200);
  delay(10);
  
  // Configure WiFi ----------------------------------------------------------
  Serial.println();
  Serial.print("Configuring access point...");
  
  WiFi.mode(WIFI_AP_STA);
  wifiMulti.addAP(ssid1, password1);
  wifiMulti.addAP(ssid2, password2);
  WiFi.softAP(APssid, APpassword);  //swapped this till last to see if mDNS works on STA now.
  
  Serial.println("Connecting ...");
//  int i = 0;
  while (wifiMulti.run() != WL_CONNECTED) { // Wait for the Wi-Fi to connect: scan for Wi-Fi networks, and connect to the strongest of the networks above
    delay(1000);
    Serial.print('.');
  }
  Serial.println('\n');
  Serial.print("Connected to ");
  Serial.println(WiFi.SSID());              // Tell us what network we're connected to
  Serial.print("IP address:\t");
  Serial.println(WiFi.localIP());           // Send the IP address of the ESP8266 to the computer

   
  // Tell the server to serve our EmbAJAX test page on root
  // installPage() abstracts over the (trivial but not uniform) WebServer-specific instructions to do so
  driver.installPage(&page, "/", updateUI);
  server.begin();

}

void updateUI() {

}

void loop() {
  static unsigned long oldTime = 0;
  // handle network. loopHook() simply calls server.handleClient(), in most but not all server implementations.
  driver.loopHook();
  if (millis() - oldTime > 2000) {
       m_script_t.setValue("25.5"); //dummy statement at the moment
           oldTime = millis();
  }

}`

**Comment by tfry-git** [comment]
I will admit that this does look like a bug in EmbAJAX, somewhere. I'll look into it, as soon as I find a bit more time. However, as a workaround for the time being, you can probably filter out those empty (or 0?) values inside your `receiveValue()` function. Probably, `if (!value) return;` will be enough.

**Comment by Win-doze** [comment]
I am sorry I keep breaking your software! I suppose I should market myself as the idiot to call in when you want to find out how to crash code.

Anyway, I appreciate you looking at this and your suggestion worked allowing me to move on to other bits of my code. I wish I knew a bit more about coding libraries (and HTML/CSS/AJAX), then I could look and see what was giving me this 'feature' and sort out my own problems.

Thank you again.

**Comment by tfry-git** [comment]
Your testing - and reporting - is much appreciated! This should now be fixed in the library, too.

**Comment by Win-doze** [comment]
Thank you!
