### ISSUE TITLE
Unchecking radio button / setting slider to default

### ISSUE THREAD

**Issue by V3N0MX92** [tfry-git/EmbAJAX#22]
Hello!

I managed to create a lot of inputs with your library and they work like a charm. However my question rather than an issue is **how can I uncheck or select a different radio button or reset a slider to a default value** from the ESP8266 program and update my Webpage? Is it even possible?

I'm using the following example (2 radio buttons and a status display):

```
const char* modes_opts[] = {"Enabled", "Disabled"};
EmbAJAXRadioGroup<2> modes("modes", modes_opts);
EmbAJAXMutableSpan radio_d("radio_d");
```

on the WebPage i'm showing showing the radio buttons and the status (selection):
```
MAKE_EmbAJAXPage(page, "My Page", "<meta http-equiv='Content-Type' content='text/html;'>",

new EmbAJAXStatic("<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">"),
new EmbAJAXStatic("<body bgcolor=""#1d2422"">"),
new EmbAJAXStatic("<table cellpadding=\"10\"><tr><td>"),
 new EmbAJAXHideableContainer<1> ("mode_text", new EmbAJAXBase*[1] {
   &modes,
}),
&radio_d,
)
```

and in UpdateUI() i use this:
`radio_d.setValue(modes_opts[modes.selectedOption()]);`

I want to use something like the following function:
```
if (hour>20 and modes.selectedOption()==0) 
{
shutDown(); // do something
and after that function is done select the Disable radio button or reset the slider 
or any other example you could think of. 
PS: I tried with modes.selectedOption()=1; but I think I'm missing something.
}
```

Any help would be deeply appreciated!
Thank you in advance!

**Comment by tfry-git** [comment]
```radio.selectOption(1);  // selects button 1
radio.selectOption(255);  // un-selects all buttons
slider.setValue(123);```

**Comment by V3N0MX92** [comment]
No, I didn't know about the API documentation. I only used the examples provided.

Thank you very much for your help. I'll read it.
