### ISSUE TITLE
ESPAsyncWebServer

### ISSUE THREAD

**Issue by csgregg** [tfry-git/EmbAJAX#24]
Trying to convert from ESPWebServer to ESPAsyncWebServer on ESP8266 but getting compile error.

Added includes <ESPAsyncTCP.h> and <EmbAJAXOutputDriverESPAsync.h> above <EmbAJAX.h> as instructed.

<EmbAJAXOutputDriverESPAsync.h> is looking for ESPAsyncWebServer but the me-no-dev/ESPAsyncWebServer library uses AsyncWebServer.

I can change the #define EmbAJAXOutputDriverWebServerClass in <EmbAJAXOutputDriverESPAsync.h> to AsyncWebServer and it compiles, but it would be good if we could switch to ESPAsyncWebServer on ESP8266 without modifying like that.

More maybe I am missing something...

Thanks!

**Comment by tfry-git** [comment]
I probably got confused due to the naming mismatch between <ESPAsyncTCP.h> and <AsyncTCP.h>. I wonder whether I actually tested the async driver on ESP8266 (I know I've used it on ESP32, myself, but not sure about the ESP8266).

Thanks!
