### ISSUE TITLE
Problem with EmbAJAXPushButton Constructors

### ISSUE THREAD

**Issue by CrusaderElectronics** [tfry-git/EmbAJAX#27]
Hi

I have noticed a problem when adding a push button (EmbAJAXPushButton) in that you need to be careful of where the declaration for the EmbAJAXOutputDriver is in the C file. From my understanding/debug if the linker/compiler puts the constructor for EmbAJAXPushButton higher up in cpu_start than the constructor for EmbAJAXOutputDriver then the program will crash. The problem appears to be the constructor for EmbAJAXPushButton is calling setBasicProperty which in turn calls setChanged which calls driver->setChanged before the driver class is ready. I think its the 'revision' variables. 

If I comment out 'setBasicProperty' in the EmbAJAXPushButton constructor everything works ok. Is it safe to leave it like this?

The main reason for asking this is that I want to separate out each webpage into a different cpp module to make the code easier to write and not have a single massive file but I can't force the linker to place the constructor for the driver first.

Attached is a decode of the backtrace.
 
[ButtonProblem.txt](https://github.com/tfry-git/EmbAJAX/files/5802141/ButtonProblem.txt)

**Comment by tfry-git** [comment]
Good catch! Of course there should not be an indirect call to setChanged(), here. I'll fix that in the next few days.

Your workaround is safe to leave like that, as long as you only want plain text inside your button (no HTML tags).
