### ISSUE TITLE
Question about conditional styling

### ISSUE THREAD

**Issue by V3N0MX92** [tfry-git/EmbAJAX#28]
Hello Thomas,

I have been using the EmbAJAX library for a lot of projects and I've added really cool styling **but always static** (colored buttons, text, boxes, transitions and everything like that).
But the problem is that I have some variables changing all the time like temperature lets say. Or an ON/OFF text when a relay is switched.

**My question is: How can I change the styling (color/size/anything in a division depending on what value a variable has with your library? Examples: strings like texts ON=green, OFF=red, TempValue >25 = red, Under 20  = blue.**

Photo example:
![thermostat](https://user-images.githubusercontent.com/59662210/106385541-79f3b580-63d9-11eb-952e-6267ecb29e7c.PNG)

I'm using HidableContainer with a div ID most of the time and style it in a text file *.css and upload the file via SPIFFS.
```

new EmbAJAXHideableContainer<1> ("status_div", new EmbAJAXBase*[1] {

   &status_d,
   
}),
```
css styling example:
```
#status_div { 
border:1px solid #dcdcdc; 
 width: 112px;
 height: 30px;
 position: absolute;
  top: -67px;
  left: 100px;
}
```
Hope you can help me with an example.
Thanks in advance!

**Comment by tfry-git** [comment]
Hi!

I'll have to admit that I have not considered this, so far.

Right now, you should be able to solve this using an EmbAJAXScriptedSpan. *Untested*:
```
auto *class_switcher = new EmbAJAXScriptedSpan("class_switcher", "this.receiveValue=function(value) { this.parentNode.class=(value ? 'warning' : 'normal'); };");

new EmbAJAXHideableContainer<1> ("status_div", new EmbAJAXBase*[1] {
   &class_switcher;
   &status_d,
})

[...]

status_d->setValue(myvalue);
class_switcher->setValue(myvalue > warning_threshold);
```

In theory, this should switch the class of the div between "normal" and "warning".

So far I have shied away from adding direct class- and/or style-support to the EmbAJAXElements. While this would be straightforward to do, it would also use more RAM in every element, whether or not classes/styles actually get changed. If my above solution works as expected, perhaps I'll add a convenience class along those lines, instead.

**Comment by V3N0MX92** [comment]
Hi ! 
Thanks for the information but unfortunately the example won't work for me.

No matter where I place the expression:

**Comment by V3N0MX92** [comment]
Hello again!

Thank you for the information but so far I couldn't manage to make what you suggested above to work... ( please also kindly understand that I'm not so advanced as you are in programming and I have some issues even figuring out the documentation of this library, sorry :( )

What I did: I placed the expression `auto *class_switcher = new EmbAJAXScriptedSpan("class_switcher", "this.receiveValue=function(value) { this.parentNode.class=(value ? 'hot' : 'cold'); };"),` in my page but always get the error "expected primary-expression before 'auto'"
You placed `;` after the expression in your example, did you mean to place it above the EmbAjaxPage? 
I think I'm missing something, what I understand is that variable class_switcher is "automatically" created depending on what type the ScriptedSpan returns (the custom javascript).

Please if you have some free time provide a simple tested example (maybe even add it later to the library examples).

Many thanks in advance!

**Comment by tfry-git** [comment]
> You placed ; after the expression in your example, did you mean to place it above the EmbAjaxPage?

Yes, this is supposed to be at the top level. Next to where you first define "status_d", for instance.

I also forgot to mention, that you will need to add ```#include<EmbAJAXScriptedSpan.h>``` below ```#include<EmbAJAX.h>```.

If this doesn't help, perhaps you can post a complete example, then it will be easier to show, where this goes, specifically. (Also, I still did not get around to actually testing my method).

**Comment by V3N0MX92** [comment]
Hello again, I didn't include the <EmbAJAXScriptedSpan.h> in the first place. This was the main issue.

I post below an example with comments, so it's easy to follow. I still have some errors commented as issue no1,2,3. 
Maybe you can help here:

[Example_Conditional.zip](https://github.com/tfry-git/EmbAJAX/files/5914420/Example_Conditional.zip)

Explanations:

I have 2 buttons, one is for adding 0.1 + and one is for subtracting 0.1 from the initial value of 20
What I would like to do: when the button_1 reaches 21 for example change the styling to hot or when button_1 is lower than 19 change styling to cold. Any simple change of colour/size would do it for me.

If you prefer the txt version you have it here:

[Example_Conditional.txt](https://github.com/tfry-git/EmbAJAX/files/5914447/Example_Conditional.txt)

Hope you can help.
Thank you !!

**Comment by tfry-git** [comment]
Here's a working example:
[class_switcher.txt](https://github.com/tfry-git/EmbAJAX/files/5921136/class_switcher.txt)

**Comment by V3N0MX92** [comment]
It works, I don't know how much memory this eats but it's super nice to be able to style elements like this. Danke dir 👍 x 💯
