### ISSUE TITLE
Button Press and Hold

### ISSUE THREAD

**Issue by G8PTN** [tfry-git/EmbAJAX#29]
Hello,
I am new to EmbAJAX and I am trying to use it on an ESP8266 D1 Mini board to provide remote control of a stepper motor.

I am using the push and hold feature EmbAJAXMomentaryButton 

Everything seems to work fine when using it with a PC Web client.
When I try using it on an Android tablet or phone, it works most of the time, but occasionally holding and releasing the button causes the action of continuously indicating the button is pressed. 
Repeated pressing and release of the button does not clear the issue, but if I refresh the page on the Android device the problem clears and the button reports “Not pressed”.
Do you have any ideas what could be causing this issue?
Many Thanks,
  Dave

**Comment by tfry-git** [comment]
Thanks for reporting. I am not sure what may be causing the button to miss the release event. As for clearing the state with a new click, the following should do the trick (please give it a try):

Change line 406 of EmbAJAX.cpp:
https://github.com/tfry-git/EmbAJAX/blob/ecbdb11f26472d0b53305698206a07844b5d4bed/EmbAJAX.cpp#L406

to read
```
"btn.onmousedown = btn.ontouchstart = function() { clearInterval(this.pinger); this.pinger=setInterval(function() {doRequest(this.id, 'p');}.bind(this),");
```

(Line 409 is what is supposed to handle the button release, normally.)

**Comment by G8PTN** [comment]
Thank you for your reply.

I have done a little more testing and was also able to get the condition also when connected to a PC, but much less frequently. I think the way it gets into the state is if there is perhaps an issue in communication between the client and server whilst the button is pressed.

I made the change you suggested on line 406 and can confirm that the state is cleared with a new click.

Again many thanks for your help, it is very much appreciated.
Dave
