### ISSUE TITLE
Display calculated value

### ISSUE THREAD

**Issue by eporocrail** [tfry-git/EmbAJAX#3]
Is it possible to display a calculated value?

**Comment by tfry-git** [comment]
EmbAJAXMutableSpan is (probably) what you are looking for. It produces a `<span>`-element, where you can set the inner content to anything you like.

See also the "Inputs"-Example, where such spans are used to simply mirror the values of the control elements. However, you can set it to calculated values just the same.

Note that you will have to convert numeric values to string, manually (`itoa()`). You can also look at the "Inputs"-Example for that.
