### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by galvanized** [tfry-git/EmbAJAX#30]
Following the Readme installation routine fails on Arduino IDE 2.0.0-beta.6 .
After selecting the .zip, I get the following. `missing header file "EmbAJAX-master.h"`

![image](https://user-images.githubusercontent.com/1581628/118314089-a4b5d580-b4c1-11eb-8d53-c4f44441966f.png)

I tried renaming the archive to `EmbAJAX.zip`. Same issue.

I tried extracting the archive, renaming the folder to EmbAJAX, then rezipping to `EmbAJAX.zip`. 
Now I get a different error. `missing file "library.properties"`.

![image](https://user-images.githubusercontent.com/1581628/118314531-45a49080-b4c2-11eb-8508-9d63603084bc.png)

**Comment by tfry-git** [comment]
Thanks for reporting. I've updated the installation instructions.
