### ISSUE TITLE
Compilation Problem with core 3.0.0 ESP8266 

### ISSUE THREAD

**Issue by Bruno999B** [tfry-git/EmbAJAX#33]
hello since installing the Arduino core 3.0.0 for ESP8266 I can no longer compile the INPUT example (LOLIN(WEMOS) D1 R2 & mini
, IDE 1.8.15). this new version of core is not / yet supported? thanks

**Comment by tfry-git** [comment]
I have not tried that yet. What is the error message you get?

Thanks!

**Comment by dftbaogh** [comment]
"
In file included from /tmp/arduino_modified_sketch_287228/AmazingAjax.ino:9:
/home/name/Arduino/libraries/EmbAJAX-master/EmbAJAXValidatingTextInput.h: In member function 'void EmbAJAXValidatingTextInput<SIZE>::print() const':
/home/name/Arduino/libraries/EmbAJAX-master/EmbAJAXValidatingTextInput.h:38:72: error: call of overloaded 'abs(unsigned int)' is ambiguous
   38 |         EmbAJAXBase::_driver->printAttribute("size", min(max(abs(SIZE-1), 10),40));  // Arbitray limit for rendered width of text fields: 10..40 chars
      |                                                                        ^
In file included from /home/name/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.0-newlib4.0.0-gnu23-48f7b08/xtensa-lx106-elf/include/c++/10.2.0/cstdlib:75,
                 from /home/name/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.0-newlib4.0.0-gnu23-48f7b08/xtensa-lx106-elf/include/c++/10.2.0/stdlib.h:36,
                 from /home/name/.arduino15/packages/esp8266/hardware/esp8266/3.0.0/cores/esp8266/Arduino.h:27,
                 from sketch/AmazingAjax.ino.cpp:1:
/home/name/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.0-newlib4.0.0-gnu23-48f7b08/xtensa-lx106-elf/include/stdlib.h:74:5: note: candidate: 'int abs(int)'
   74 | int abs (int);
      |     ^~~
In file included from /home/name/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.0-newlib4.0.0-gnu23-48f7b08/xtensa-lx106-elf/include/c++/10.2.0/cstdlib:77,
                 from /home/name/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.0-newlib4.0.0-gnu23-48f7b08/xtensa-lx106-elf/include/c++/10.2.0/stdlib.h:36,
                 from /home/name/.arduino15/packages/esp8266/hardware/esp8266/3.0.0/cores/esp8266/Arduino.h:27,
                 from sketch/AmazingAjax.ino.cpp:1:
/home/name/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.0-newlib4.0.0-gnu23-48f7b08/xtensa-lx106-elf/include/c++/10.2.0/bits/std_abs.h:79:3: note: candidate: 'constexpr long double std::abs(long double)'
   79 |   abs(long double __x)
      |   ^~~
/home/name/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.0-newlib4.0.0-gnu23-48f7b08/xtensa-lx106-elf/include/c++/10.2.0/bits/std_abs.h:75:3: note: candidate: 'constexpr float std::abs(float)'
   75 |   abs(float __x)
      |   ^~~
/home/name/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.0-newlib4.0.0-gnu23-48f7b08/xtensa-lx106-elf/include/c++/10.2.0/bits/std_abs.h:71:3: note: candidate: 'constexpr double std::abs(double)'
   71 |   abs(double __x)
      |   ^~~
/home/name/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.0-newlib4.0.0-gnu23-48f7b08/xtensa-lx106-elf/include/c++/10.2.0/bits/std_abs.h:61:3: note: candidate: 'long long int std::abs(long long int)'
   61 |   abs(long long __x) { return __builtin_llabs (__x); }
      |   ^~~
/home/name/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.0-newlib4.0.0-gnu23-48f7b08/xtensa-lx106-elf/include/c++/10.2.0/bits/std_abs.h:56:3: note: candidate: 'long int std::abs(long int)'
   56 |   abs(long __i) { return __builtin_labs(__i); }
      |   ^~~
exit status 1
Error compiling for board Generic ESP8266 Module.

"

I believe this is a python 3 compatibility issue

Use board version 2.7.4 for now.

**Comment by tfry-git** [comment]
This particular problem should be fixed, now, so if you have an easy way to test, that would be very welcome.

I still did not find the time to try the new core, myself, however, so it is possible that there are more problems lingering.

**Comment by Bruno999B** [comment]
i just tested, it works fine now, i haven't seen any other issues yet. thank you so much.

**Comment by tfry-git** [comment]
Great! Thanks for testing. I'm closing this ticket, then. If you run into anything else, don't hesitate to open another.
