### ISSUE TITLE
Preset text field

### ISSUE THREAD

**Issue by siegmar** [tfry-git/EmbAJAX#36]
Sorry, I have another question. I want to implement a form with the lib for entering the system parameters. 
The system parameters are then saved with the littlfs file system. When the form is reloaded, the saved values should then be displayed. 

The presetting works with the EmbAJAXCheckButton as follows : 

EmbAJAXCheckButton check("check", "Some option",1);    // Set  CheckButton  
EmbAJAXCheckButton check("check", "Some option",0);    // Reset  CheckButton  
EmbAJAXMutableSpan check_d("check_d");

For entering the SSID I use : 

EmbAJAXTextInput<BUFLEN> text("text");  // Text input, width BUFLEN
EmbAJAXMutableSpan text_d("text_d");
char text_d_buf[BUFLEN];

Now the question, how can I now transfer my saved text to the text field, i.e. pre-populate EmbAJAXTextInput.
Thanks in advance
Cheers
Siegmar

**Comment by tfry-git** [comment]
```text.setValue("initial");``` (probably called near the end of setup())

Most ```EmbAJAXElement```s have a function for changing the value from the server side, at any time that you like (called ```setXYZ()```). The only thing you need to worry about yourself is not overwriting values that have been set from the client.

**Comment by siegmar** [comment]
Thank you so much for your help , it is working well.
cheers
Siegmar
