### ISSUE TITLE
Add CSS styling to control

### ISSUE THREAD

**Issue by Ostpopcorn** [tfry-git/EmbAJAX#4]
Hi,
How do I add style to a control since I (think) can't add a CSS class to the button HTML. I kinda new to messing around with all of this so am I missing something or doing anything wrong?
The pupose of this is to make the buttons larger and more colorful. For example with this styling `.button { border: none; color: white; padding: 10px 20px;text-decoration: none; font-size: 20px; margin: 2px;}`

**Comment by tfry-git** [comment]
There is not currently any support for adding a class to an individual EmbAJAX element, and I'm not sure it makes sense to add, as it would increase RAM usage, unconditionally.

However, what you can do:
- Add a CSS spec to the entire page: ```EmbAJAXPage()``` accepts a ```header_add``` parameter to add custom code to the HTML header. So you can add a style like this (for example): ```MAKE_EmbAJAXPage(page, "MyTitle", "<style>button {color: red;}</style>", ...)```
- If you want to style individual elements, you can also refer to them by their ```id```-parameter (e.g. ```#mybutton{font-weight: bold;}```
- If you want to style a group of elements, consider placing them in a named ```<div>```: ```EmbAJAXHideableContainer```.
- You could also use ```EmbAJAXStatic``` to add a custom ```<span>```-element around other elements, although that is probably not good style.

**Comment by tfry-git** [comment]
As I have now added an example to the sources, I'm closing this issue.
