### ISSUE TITLE
Include " versus < mix

### ISSUE THREAD

**Issue by FedericoBusero** [tfry-git/EmbAJAX#41]
When using the library locally (install in the same directory as the project, not installed in the central Arduino directory) it gives compilation errors because the library mixes
#include <
#include "
and so it mixes local and global files.

I would like to do a PR where all includes use " , so that the local file will be used if available. Is this ok?

**Comment by tfry-git** [comment]
Yes, please go ahead. All library local files should be ```#include "```ed, of course.

**Comment by FedericoBusero** [comment]
I created a PR to fix it,
https://github.com/tfry-git/EmbAJAX/pull/42

**Comment by tfry-git** [comment]
Thanks for you work!
