### ISSUE TITLE
problem with page refreshing

### ISSUE THREAD

**Issue by Bruno999B** [tfry-git/EmbAJAX#50]
Hello, first of all thank you for your extraordinary work!
I have a problem with which I cannot resolve, in the following code if I activate "ContenuPageWeb.setValue(mybufferPageWeb, true);" in updateUI() the page no longer refreshes itself every second, but manual refreshing still works. I don't understand why... Can you help me?
Thank You

```
#include <WiFi.h>
const char* ssid     = "*******";
const char* password = "********";
uint32_t i1 = 0;
#include <EmbAJAX.h>
EmbAJAXOutputDriverWebServerClass server(80);
EmbAJAXOutputDriver driver(&server);
EmbAJAXMutableSpan ContenuPageWeb("ContenuPageWeb");
char mybufferPageWeb[300];
EmbAJAXMutableSpan button_d("button_d");
char button_d_buf[30];

MAKE_EmbAJAXPage(page1, "TEST ", "",
                 &ContenuPageWeb,
                 &button_d,
                )

void setup() {
  Serial.begin(115200);
  WiFi.mode(WIFI_STA);
  IPAddress ip(192, 168, 0, 199);
  IPAddress gateway(192, 168, 50, 1);
  IPAddress subnet(255, 255, 0, 0);

  WiFi.config(ip, gateway, subnet);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(F("."));
  }
  Serial.println();
  Serial.println(F("WiFi connected"));
  server.begin();
  Serial.println(F("Server started"));
  Serial.println(WiFi.localIP());

  driver.installPage(&page1, "/", updateUI);
  server.begin();
  updateUI();
}

void updateUI() {
  //ContenuPageWeb.setValue(mybufferPageWeb, true);
  button_d.setValue(itoa(i1, button_d_buf, 10));
}

void loop() {
  driver.loopHook();
  delay(1000);
  i1++;
  String ligne = "";
  ligne += String(i1);
  ligne += "<br>\n";
  
  sprintf(mybufferPageWeb, ligne.c_str());
  updateUI();
}

```

**Comment by tfry-git** [comment]
I have taken a cursory look, only, so far. However, I believe the problem may be simply that mybufferPageWeb is not yet initialized during your first call to updateUI() (from within setup()) -> undefined behavior. Try initializing to "" before that.

**Comment by Bruno999B** [comment]
Thank you for your reply. I tried something like this but it doesn't change the problem.

```
#include <WiFi.h>
const char* ssid     = "********";
const char* password = "**********";
uint32_t i1 = 0;
#include <EmbAJAX.h>
EmbAJAXOutputDriverWebServerClass server(80);
EmbAJAXOutputDriver driver(&server);
EmbAJAXMutableSpan ContenuPageWeb("ContenuPageWeb");
char mybufferPageWeb[300];
MAKE_EmbAJAXPage(page1, "TEST ", "", &ContenuPageWeb,)

void setup() {
  Serial.begin(115200); while (!Serial);
  WiFi.mode(WIFI_STA);
  IPAddress ip(192, 168, 0, 199);
  IPAddress gateway(192, 168, 50, 1);
  IPAddress subnet(255, 255, 0, 0);
  WiFi.config(ip, gateway, subnet);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(F("."));
  }
  Serial.println();
  Serial.println(F("WiFi connected"));
  server.begin();
  Serial.println(F("Server started"));
  Serial.println(WiFi.localIP());

  constructwebpage();
  Serial.println(mybufferPageWeb);

  driver.installPage(&page1, "/", updateUI);
  server.begin();

  updateUI();
}

void updateUI() {
  ContenuPageWeb.setValue(mybufferPageWeb, true);
}

void loop() {
  driver.loopHook();
  delay(1000);
  i1++;
  constructwebpage();
  updateUI();
}

void constructwebpage() {
  String ligne = "";
  ligne += String(i1);
  ligne += "<br>\n";
  sprintf(mybufferPageWeb, ligne.c_str());
}
```

**Comment by tfry-git** [comment]
Ok, still no actual testing done (I might get around to do some, tomorrow), but another problem in your code is the ```delay(1000)```. During those delays, the web server will not be able to service anything at all. Conceivably this will result in requests clogging up really quickly.

Try rewriting your loop like so:
```
uint32_t last_update = 0;
void loop() {
  driver.loopHook();
  if (millis() - last_update > 1000) {
    last_update = millis();
    i1++;
    constructwebpage();
    updateUI();
  }
}
```

**Comment by Bruno999B** [comment]
The delay function is used in this code because it is just for the experiment.  in my real program I use non-blocking code.  the problem is the same.  even with a delay and an int variable it works (as in the first code), while with a string it blocks the refresh.  I tried different string->char conversion methods, nothing works... I'm out of ideas, thanks for your help

**Comment by tfry-git** [comment]
Sorry for trying hard to deny this (important) bug, earlier. Turns out the key ingredient, here, was  the newline character inside the span's value. This didn't get the proper escaping during transmission. Apparently, I never tested that.

**Comment by Bruno999B** [comment]
It doesn't matter, I've been using your library for years, until now this problem has never caused me a problem.
I applied the fix, it works flawlessly, thank you very much! good work !!
