### ISSUE TITLE
Change from selection back to 0 selection

### ISSUE THREAD

**Issue by eporocrail** [tfry-git/EmbAJAX#6]
Is it possible to go back to  no selection after reading the selection?
What I mean is: I have a radio selector. Normally there is nothing selected. After the selection is done, the value is taken. Than I would like to set the selector back to 0.

**Comment by tfry-git** [comment]
I did not test right now, but ```radio->selectOption(-1)``` should do the trick, in theory.

**Comment by eporocrail** [comment]
Not completely correct:
"base operand of '->' has non-pointer type 'EmbAJAXRadioGroup<3u>'"

**Comment by tfry-git** [comment]
Well, ```radio.selectOption(-1)```, then.

**Comment by eporocrail** [comment]
This works quite well for "RadioGroup" and "OptionSelect".
Is there a way to insert "false" or "true" in "CheckButton" ?
