### ISSUE TITLE
Text input field does not reflect value from .setValue()

### ISSUE THREAD

**Issue by eporocrail** [tfry-git/EmbAJAX#7]
I took your example file and made a change to it:

text_d.setValue(strncpy(text_d_buf, text.value(), BUFLEN));

	if(m_button.status() == 0) {
		text.setValue("hallo");
	}

I insert some value in the text field. text_d reflects this value.
When I push the momentary button the value in text is not changed. the value in text_d reflects "hallo"

Would you be so kind and look into this issue?

**Comment by tfry-git** [comment]
Hi!

I think, it's probably a missing ```setChanged();``` inside ```EmbAJAXTextInput::setValue()```. Could you test that theory for me, by adding ```setChanged();``` below line 341 of EmbAJAX.h (https://github.com/tfry-git/EmbAJAX/blob/491bf4fee01b1e9b8566ec9575cf5eed79c6033a/EmbAJAX.h#L341)?

**Comment by eporocrail** [comment]
Hi Thomas

That does the trick.

Ellard

**Comment by tfry-git** [comment]
Thanks for testing! Fix committed.
