### ISSUE TITLE
Optical signal

### ISSUE THREAD

**Issue by eporocrail** [tfry-git/EmbAJAX#9]
Hallo Thomas

Would it be possible to have an optical signal like your status indicator.
I would need a sign (shape is less relevant, but a small circle would be nice) which changes colour based on an incoming message in my system.

Ellard

**Comment by tfry-git** [comment]
Hi!

It may make sense to add something like this, out of the box.

However, you can achieve this relatively easily, using an EmbAJAXMutableSpan. You'd then use something like:
```myspan.setValue("<span style=\"background-color:red;\">ALARM</span>");```
or (circle):
```myspan.setValue("<span style=\"border-radius:50%; background-color:green;\">G</span>");```
And of course you'd change the value depending on the current status.

**Comment by eporocrail** [comment]
Hi

It does not work. The complete text is displayed
It tried several things but nothing works
![Text](https://user-images.githubusercontent.com/19239290/63342273-58b91980-c34b-11e9-978a-c89a67395669.jpg)

**Comment by tfry-git** [comment]
Sorry, my bad. You will need
```myspan.setValue("<span style=\"border-radius:50%; background-color:green;\">G</span>", true);```

Note the extra argument ```true``` at the end, to allow HTML.

**Comment by eporocrail** [comment]
It works!

Great library!
